name: choy_ritur_golpo
description: Weather and season application for Bangladeshi people

publish_to: "none"

version: 1.1.0+8

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  gap: ^3.0.1
  dio: ^5.8.0+1
  intl: ^0.20.2
  shimmer: ^3.0.0
  latlong2: ^0.9.1
  timezone: ^0.10.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  home_widget: ^0.7.0+1
  restart_app: ^1.3.2
  flutter_map: ^8.1.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  iconsax_plus: ^1.0.0
  dynamic_color: ^1.7.0
  path_provider: ^2.1.5
  # quick_settings: ^1.0.1
  json_annotation: ^4.9.0
  flutter_timezone: ^4.1.0
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  freezed_annotation: ^3.0.0
  flutter_map_cache: ^2.0.0+1
  flutter_displaymode: ^0.6.0
  lat_lng_to_timezone: ^0.2.0
  line_awesome_flutter: ^3.0.1
  dio_cache_interceptor: ^4.0.3
  http_cache_file_store: ^2.0.1
  flutter_map_animations: ^0.9.0
  flutter_expandable_fab: ^2.4.1
  flutter_hsvcolor_picker: ^1.5.1
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^19.1.0
  internet_connection_checker_plus: ^2.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  bangla_utilities: ^1.5.0
  google_mobile_ads: ^6.0.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.17.5
  # firebase_auth: ^4.16.0
  shared_preferences: ^2.2.2

# Uncomment this for publishing FLOSS variant
# dependency_overrides:
#   geolocator_android:
#     git:
#       url: https://github.com/Zverik/flutter-geolocator.git
#       ref: floss
#       path: geolocator_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0.dev
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#87CEFA"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#87CEFA"
  android_12:
    color: "#87CEFA"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/seasons/
    - assets/geo/geo_with_lat_lon.json
